package:
  name: cyrasterize
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy 1.10.*
    - cython 0.21.*
    - glew 1.11.0
    - glfw3 3.0.4
    - msinttypes r26 [win]

  run:
    - python
    - numpy 1.10.*
    - glew 1.11.0 [unix]
    - glfw3 3.0.4 [unix]

about:
  home: https://github.com/menpo/cyrasterize/
  license: BSD
