package:
  name: cyrasterize
  version: {{ environ['CYRASTERIZE_VERSION'] }}

requirements:
  build:
    - python
    - distribute
    - numpy
    - cython
    - glew
    - glfw3
    - msinttypes [win]

  run:
    - python
    - numpy
    - glew [unix]
    - glfw3 [unix]

about:
  home: https://github.com/menpo/cyrasterize/
  license: BSD
